### ISSUE TITLE
Include relay in events

### ISSUE THREAD

**Issue by npub1zenn0** [sepehr-safari/nostr-hooks#5]
That info would be needed for creating `nprofile`, `nevent` identifiers, and in tagging relay into events `['r', 'wss://relay.url']` for e.g. reactions.

**Comment by sepehr-safari** [comment]
Events have an standard type which is described here as NIP-01: https://github.com/nostr-protocol/nips/blob/master/01.md
you as the developer already have the relay values. they are as the same relays as you use to subscribe to events or as well as publishing a new event.
you can provide more details about your problem if it still exists, or verify that it's resolved.

**Comment by npub1zenn0** [comment]
What I mean is that not every event comes in from every relay I subscribe to, and in order to link to an event I can use an `nevent` which is essentially `{ relays: [...relays this event was found on], id: "eventid" }`.

Putting in every relay I subscribe to is sorta fine as a workaround, I guess, even though not completely accurate.

**Comment by sepehr-safari** [comment]
one of the tricks you can do is to use multiple separate useSubscribe hooks with different relays on each. with this approach you can have multiple event object which are grouped by their corresponding relays.
nostr-hooks will do all the batchings on behalf, so no extra subscription/connection will be used.
you can create a custom hook for these kind of custom functionalities.
