### ISSUE TITLE
TypeError when building react app

### ISSUE THREAD

**Issue by kiwiidb** [sepehr-safari/nostr-hooks#6]
I previously added nostr-hooks as a dependency to [this project](https://github.com/kiwiidb/nostr-photobooth/)

When deployed on Vercel , the page failed to load with the following error:

```
Uncaught TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at weierstrass.ts:1097:22
    at weierstrass.ts:1166:21
    at secp256k1.ts:249:16
    at index.js:17:1
    at index.js:17:1
```

**Comment by sepehr-safari** [comment]
it's nothing related to nostr-hook. the error message is explaining itself. just don't convert a BigInt to a number!
I've checked your code base, it's already showing that error while there is no nostr-hooks as a dependency.

**Comment by sepehr-safari** [comment]
it might be something related to your browsers list in `package.json`

```
"browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```

try using modern versions for production.

btw, Create React App is already deprecated, try using [Vite](https://vitejs.dev/)

**Comment by sepehr-safari** [comment]
I'm closing this issue, since you have successfully upgraded your project to Vite and Nostr-Hooks.
