### ISSUE TITLE
Error: No "exports" main defined in /node_modules/nostr-hooks/package.json

### ISSUE THREAD

**Issue by 0x1nexus** [sepehr-safari/nostr-hooks#8]
I tried using this in a remix app and Im having some issues when I tried building it.

**Comment by 0x1nexus** [comment]
<img width="500" alt="image" src="https://github.com/sepehr-safari/nostr-hooks/assets/106025693/516d68df-4cbd-406f-99dd-1c5833f7ac68">

But Im sure its installed, I look into my node_modules its there.

**Comment by sepehr-safari** [comment]
how do you try to import nostr-hooks? can you provide your import statement?
how about your package.json dependencies? are you using proper package version?

**Comment by Nileshdcool** [comment]
You can simply replicate it by creating fres remix app 

npx create-remix@latest

https://remix.run/docs/en/1.19.3/tutorials/jokes

then install react hooks package the latest version , the node I am using is 20.5.1 , 

and then simply add hooks package on index page to experiment with 

`import type { V2_MetaFunction } from "@remix-run/node";
import { useSubscribe } from 'nostr-hooks';
import { useState } from "react";

export const meta: V2_MetaFunction = () => {
  return [
    { title: "New Remix App" },
    { name: "description", content: "Welcome to Remix!" },
  ];
};

export default function Index() {
  const [toggle, setToggle] = useState(false);

  const { events, eose } = useSubscribe({
    relays: ['wss://relay.damus.io'],
    filters: [{ authors: ['pubkey1'], kinds: [1], limit: 10 }],
    options: {
      enabled: toggle,
      force: false,
      batchingInterval: 500,
      invalidate: false,
      closeAfterEose: true,
    },
  });

  if (!events && !eose) return <p>Loading...</p>;

  return (
    <>
      <button onClick={() => setToggle(!toggle)}>Toggle</button>

      <ul>
        {events.map((event) => (
          <li key={event.id}>
            <p>{event.pubkey}</p>
            <p>{event.kind}</p>
            <p>{event.id}</p>
          </li>
        ))}
      </ul>
    </>
  );
}
`

My package.json file 

`{
  "private": true,
  "sideEffects": false,
  "scripts": {
    "build": "remix build",
    "dev": "remix dev",
    "start": "remix-serve build",
    "typecheck": "tsc"
  },
  "dependencies": {
    "@remix-run/css-bundle": "^1.19.3",
    "@remix-run/node": "^1.19.3",
    "@remix-run/react": "^1.19.3",
    "@remix-run/serve": "^1.19.3",
    "isbot": "^3.6.8",
    "nostr-hooks": "^1.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@remix-run/dev": "^1.19.3",
    "@remix-run/eslint-config": "^1.19.3",
    "@types/react": "^18.0.35",
    "@types/react-dom": "^18.0.11",
    "eslint": "^8.38.0",
    "typescript": "^5.0.4"
  },
  "engines": {
    "node": ">=14.0.0"
  }
}
`

**Comment by sepehr-safari** [comment]
try adding this line of setting in your remix config file:

``` remix.config.ts
/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  serverDependenciesToBundle: ["nostr-hooks"],
};
```

`nostr-hooks only exports as ESM module, and Remix is just supporting CJS modules at the moment. they are trying to have a shift to ESM modules -as it's the future- but for now, you have to set this line of configuration.`

please let me know if the issue is resolved.

read more about this issue on Remix docs:
[Gotchas | Remix : Importing ESM Packages](https://remix.run/docs/en/main/pages/gotchas#importing-esm-packages)

**Comment by Nileshdcool** [comment]
@sepehr-safari  => this solution didn't work , it is still the same error. 

/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  erverDependenciesToBundle: ["nostr-hooks"],
  cacheDirectory: "./node_modules/.cache/remix",
  future: {
    v2_errorBoundary: true,
    v2_meta: true,
    v2_normalizeFormMethod: true,
    v2_routeConvention: true,
  },
  ignoredRouteFiles: ["**/.*", "**/*.test.{js,jsx,ts,tsx}"],
  postcss: true,
  serverModuleFormat: "cjs",
  tailwind: true,
};

**Comment by sepehr-safari** [comment]
>  erverDependenciesToBundle: ["nostr-hooks"],


did you miss spelled `erverDependenciesToBundle` ? I think there is a missing `s` at the beginning!

**Comment by neilsukalikar** [comment]
can you explain which s you are talking about , I have used exactly the way you shared this settings with me here

`erverDependenciesToBundle: ["nostr-hooks"],`

**Comment by sepehr-safari** [comment]
it's not `erverDependenciesToBundle`
the first word is not `erver` it's `server`
